name: deploiement-container

on:
  push:
    branches:
      - main
    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directory: ./packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifiez le code source
      - uses: actions/checkout@v2

      # Étape 2 : Installez les dépendances
      - run: npm install

      # Étape 3 : Construisez le projet
      - run: npm run build

      # Étape 4 : Synchronisez avec AWS S3
      - name: Synchronize to S3
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-3
