name: deploiement-container

on:
  push:
    branches:
      - main
    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directory: ./packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifiez le code source
      - uses: actions/checkout@v2

      # Étape 2 : Installez les dépendances
      - run: npm install

      # Étape 3 : Construisez le projet
      - run: npm run build

      # Étape 4 : Déployer sur GitHub Pages
      - name: Déployer sur GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
